//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teachercrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_details
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string DOB { get; set; }
        public string Gender { get; set; }
        public string CNIC { get; set; }
        public string FatherName { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<int> Contact { get; set; }
    }
}
